function expowiska.core.print_start_message()
    scripts:print_log("Uzywasz pluginu arkadia-expowiska, ver. " .. expowiska.version .. ". Pomoc dostepna w '/exp_pomoc'")
end

function expowiska.alias.print_help()
    cecho("\n <green>Arkadia skrypt expowiska, ver " .. string.sub(expowiska.version .. "   ", 0, 5) .. "\n")
    cecho("\n")
    cecho(" <yellow>Dostepne aliasy uzytkowe:<grey>\n")
    cecho("\n")
    cecho("<light_slate_blue>/exp_pomoc<grey> - pokazuje pomoc, ktora czytasz.\n")
	cecho("<light_slate_blue>/exp_zabij1 <opis><grey> - Pozwala na reczne dodanie binda pod <light_slate_blue>ALT+Z\n")
	cecho("<light_slate_blue>/exp_zabij2 <opis><grey> - Pozwala na reczne dodanie binda pod <light_slate_blue>ALT+X\n")
	cecho("<light_slate_blue>/exp_zabij3 <opis><grey> - Pozwala na reczne dodanie binda pod <light_slate_blue>ALT+C\n")
	cecho("<light_slate_blue>/exp_zabij4 <opis><grey> - Pozwala na reczne dodanie binda pod <light_slate_blue>ALT+V\n")
	cecho("<orange>Uwaga!<grey> - Skrypt nie odmienia nazw. Trzeba wpisywac dokladnie tak jak zostanie wyslane do muda. \n")
	cecho("<light_slate_blue>/exp_pokaz<grey> - Pozwala wyswielic obecne bindy <light_slate_blue>ALT+Z,X,C,V\n")
	cecho("<light_slate_blue>SHIFT+ALT+Z,X,C,V<grey> - Pozwala na przelamanie celu podbindowanego na <light_slate_blue>ALT+Z,X,C,V\n\n")
	-- Ishtar
    cecho(" <yellow>Ishtar:<grey>\n")
	cechoLink("<light_slate_blue>/nieumarli", [[expandAlias("/nieumarli")]], "/nieumarli", true)   
    cecho("<grey> - ustawia expowisko na Nieumarlych\n")
    cechoLink("<light_slate_blue>/sztolnia", [[expandAlias("/sztolnia")]], "/sztolnia", true)   
    cecho("<grey> - ustawia expowisko na Sztolnie w Mahakamie\n")
    cechoLink("<light_slate_blue>/zboje", [[expandAlias("/zboje")]], "/zboje", true)   
    cecho("<grey> - ustawia expowisko na Zboje\n\n")
    -- Imperium
	cecho(" <yellow>Imperium:<grey>\n")
    cechoLink("<light_slate_blue>/banici", [[expandAlias("/banici")]], "/banici", true)   
    cecho("<grey> - ustawia expowisko na Banici\n")
    cechoLink("<light_slate_blue>/bagna", [[expandAlias("/bagna")]], "/bagna", true)   
    cecho("<grey> - ustawia expowisko na Bagnach Ghouli\n")
    cechoLink("<light_slate_blue>/campo", [[expandAlias("/campo")]], "/campo", true)   
    cecho("<grey> - ustawia expowisko na Cmentarz Campogrotta\n")
	cechoLink("<light_slate_blue>/kasztel", [[expandAlias("/kasztel")]], "/kasztel", true)   
    cecho("<grey> - ustawia expowisko na Kasztel Barona Poitielers\n")
	cechoLink("<light_slate_blue>/skaveni", [[expandAlias("/skaveni")]], "/skaveni", true)   
    cecho("<grey> - ustawia expowisko na skavenach\n")
	cechoLink("<light_slate_blue>/troglodyci", [[expandAlias("/troglodyci")]], "/troglodyci", true)   
    cecho("<grey> - ustawia expowisko na Troglodyci\n")
	cechoLink("<light_slate_blue>/wsiowe", [[expandAlias("/wsiowe")]], "/wsiowe", true)   
    cecho("<grey> - ustawia expowisko na Orki Wsiowe\n")  
	cechoLink("<light_slate_blue>/wezen", [[expandAlias("/wezen")]], "/wezen", true)   
    cecho("<grey> - ustawia expowisko na Ruiny Wezendorf\n")
	cechoLink("<light_slate_blue>/zjawy", [[expandAlias("/zjawy")]], "/zjawy", true)   
    cecho("<grey> - ustawia expowisko na Zjawach\n")
	-- Administracyjne
	cecho("\n <yellow>Aliasy administracyjne:<grey>\n\n")
    cechoLink("<light_slate_blue>/expowiska_przeinstaluj_plugin", [[expandAlias("/expowiska_przeinstaluj_plugin")]], "/expowiska_przeinstaluj_plugin", true)   
    cecho("<grey> - odinstalowuje ten plugin i instaluje aktualna wersje\n")
	cecho("<orange>Uwaga!<grey> - Po reinstalacji prosze obowiazkowo zrestartowac mudleta. \n")
    cecho("\n")
end